Ext.define('xf.model.project.Project', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'ID',
        text: ''
    }, {
        name: 'CompanyID',
        text: '公司ID'
    }, {
        name: 'Company.Name',
        text: '公司名称'
    }, {
        name: 'UserID',
        text: '用户ID'
    }, {
        name: 'ProjectNo',
        dtype: 'string',
        text: '项目代码'
    }, {
        name: 'ProjectName',
        dtype: 'string',
        text: '项目名称'
    }, {
        name: 'ContractNo',
        dtype: 'string',
        text: ''
    }, {
        name: 'CustomerName',
        dtype: 'string',
        text: ''
    }, {
        name: 'CreateUser',
        dtype: 'string',
        text: '创建用户'
    }, {
        name: 'CreateDate',
        dtype: 'date',
        text: '创建日期'
    }, {
        name: 'ProjectStatus',
        text: '项目状态'
    }, {
        name: 'ModelID',
        text: '井道模型ID'
    }, {
        name: 'ProjectVerNo',
        dtype: 'string',
        text: '版本号'
    }, {
        name: 'ParentID',
        text: '来源项目'
    }, {
        name: 'DrawingTaskID',
        text: ''
    }, {
        name: 'DrawingTask.TaskStatus',
        text: '任务状态'
    }, {
        name: 'Remark',
        dtype: 'string',
        text: '描述'
    }, {
        name: 'Status',
        text: ''
    }, {
        name: 'CreateOn',
        dtype: 'date',
        text: ''
    }, {
        name: 'CreateBy',
        text: ''
    }, {
        name: 'UpdateOn',
        dtype: 'date',
        text: ''
    }, {
        name: 'UpdateBy',
        text: ''
    }],
    idProperty: 'ID'
});