//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Yanjun.Framework.Service.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CadClientServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CadClientService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadBlockFromDwgFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCadDrawingTaskOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CadClientService() {
            this.Url = global::Yanjun.Framework.Service.Properties.Settings.Default.Yanjun_Framework_Service_WebReference_CadClientService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadBlockFromDwgFileCompletedEventHandler UploadBlockFromDwgFileCompleted;
        
        /// <remarks/>
        public event CreateCadDrawingTaskCompletedEventHandler CreateCadDrawingTaskCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadBlockFromDwgFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CadDrawingReturnObj UploadBlockFromDwgFile(string blockDwgFileUrl) {
            object[] results = this.Invoke("UploadBlockFromDwgFile", new object[] {
                        blockDwgFileUrl});
            return ((CadDrawingReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void UploadBlockFromDwgFileAsync(string blockDwgFileUrl) {
            this.UploadBlockFromDwgFileAsync(blockDwgFileUrl, null);
        }
        
        /// <remarks/>
        public void UploadBlockFromDwgFileAsync(string blockDwgFileUrl, object userState) {
            if ((this.UploadBlockFromDwgFileOperationCompleted == null)) {
                this.UploadBlockFromDwgFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadBlockFromDwgFileOperationCompleted);
            }
            this.InvokeAsync("UploadBlockFromDwgFile", new object[] {
                        blockDwgFileUrl}, this.UploadBlockFromDwgFileOperationCompleted, userState);
        }
        
        private void OnUploadBlockFromDwgFileOperationCompleted(object arg) {
            if ((this.UploadBlockFromDwgFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadBlockFromDwgFileCompleted(this, new UploadBlockFromDwgFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCadDrawingTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CadDrawingReturnObj CreateCadDrawingTask(string cadDrawingArgsJson, string taskCode) {
            object[] results = this.Invoke("CreateCadDrawingTask", new object[] {
                        cadDrawingArgsJson,
                        taskCode});
            return ((CadDrawingReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCadDrawingTaskAsync(string cadDrawingArgsJson, string taskCode) {
            this.CreateCadDrawingTaskAsync(cadDrawingArgsJson, taskCode, null);
        }
        
        /// <remarks/>
        public void CreateCadDrawingTaskAsync(string cadDrawingArgsJson, string taskCode, object userState) {
            if ((this.CreateCadDrawingTaskOperationCompleted == null)) {
                this.CreateCadDrawingTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCadDrawingTaskOperationCompleted);
            }
            this.InvokeAsync("CreateCadDrawingTask", new object[] {
                        cadDrawingArgsJson,
                        taskCode}, this.CreateCadDrawingTaskOperationCompleted, userState);
        }
        
        private void OnCreateCadDrawingTaskOperationCompleted(object arg) {
            if ((this.CreateCadDrawingTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCadDrawingTaskCompleted(this, new CreateCadDrawingTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CadDrawingReturnObj {
        
        private bool successField;
        
        private string messageField;
        
        private string returnStringField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnString {
            get {
                return this.returnStringField;
            }
            set {
                this.returnStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void UploadBlockFromDwgFileCompletedEventHandler(object sender, UploadBlockFromDwgFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadBlockFromDwgFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadBlockFromDwgFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CadDrawingReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CadDrawingReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CreateCadDrawingTaskCompletedEventHandler(object sender, CreateCadDrawingTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCadDrawingTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCadDrawingTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CadDrawingReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CadDrawingReturnObj)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591