Ext.define("xf.view.org.Company", {
    extend: 'Ext.panel.Panel',
    padding: 0,
    layout: 'border',
    frame: false,
    border: 0,
    controller: 'company',
    title: '公司管理',
    items: [{
        xtype: 'panel',
        region: 'center',
        itemId: 'content',
        reference: 'content',
        layout: 'card',
        items: [{
            xtype: "sggrid",
            region: 'center',
            columns: [{
                text: '行号', xtype: 'rownumberer',
                width: 50,
                sortable: false
            }, {
                text: 'ID',
                dataIndex: 'ID',
                hidden: true
            }, {
                text: '编号',
                dataIndex: 'Code',
                width: 100
            }, {
                text: '名称',
                dataIndex: 'Name',
                width: 150
            }, {
                text: '地址',
                dataIndex: 'Address',
                width: 150
            }, {
                text: '电话',
                dataIndex: 'Tel',
                width: 100
            }, {
                text: '邮件',
                dataIndex: 'Email',
                width: 100
            }, {
                text: '规模',
                dataIndex: 'Scale',
                width: 100
            }, {
                text: '级别',
                dataIndex: 'Level',
                width: 100
            }, {
                text: '创建日期',
                dataIndex: 'CreateOn',
                width: 100,
                renderer: Ext.util.Format.dateRenderer('m/d/Y')
            }, {
                text: '描述',
                dataIndex: 'Remark',
                width: 150
            }],
            listeners: {
                beforeload: "companyBeforeload"
            },
            quickSearchCols: ['Name', 'Code'],
            controllerUrl: 'Company',
            modelName: 'xf.model.org.Company',
            selfButtons: [SG_BUTTONS.ADD, SG_BUTTONS.EDIT, SG_BUTTONS.DELETE]
        }, {
            xtype: 'SGForm',
            apiUrl: '/api/Company',
            includePath: [],
            items: [{
                xtype: 'textfield',
                fieldLabel: '编号',
                allowBlank: false,
                afterLabelTextTpl: REQUIRED_LABEL_TPL,
                name: 'Code'
            }, {
                xtype: 'textfield',
                fieldLabel: '名称',
                allowBlank: false,
                afterLabelTextTpl: REQUIRED_LABEL_TPL,
                name: 'Name'
            }, {
                xtype: 'textfield',
                fieldLabel: '地址',
                name: 'Address'
            }, {
                xtype: 'textfield',
                fieldLabel: '电话',
                name: 'Tel'
            }, {
                xtype: 'datefield',
                fieldLabel: '创建时间',
                readOnly: true,
                name: 'CreateOn',
                format: "Y-m-d\\TH:i:s"
            }, {
                xtype: 'textfield',
                fieldLabel: '邮件',
                name: 'Email'
            }, {
                xtype: 'textfield',
                fieldLabel: '规模',
                name: 'Scale'
            }, {
                xtype: 'numberfield', allowDecimals: false,
                fieldLabel: '级别',
                name: 'Level'
            }, {
                xtype: 'textarea',
                columnWidth: 1,
                fieldLabel: '描述',
                name: 'Remark'
            }],
            selfButtons: [SG_BUTTONS.SAVE, SG_BUTTONS.EDIT, SG_BUTTONS.BACK]
        }]
    }]
});