Ext.define("xf.view.project.Project", {
    extend: 'Ext.panel.Panel',
    padding: 0,
    layout: 'border',
    frame: false,
    border: 0,
    controller: 'project',
    title: '项目管理',
    items: [{
        xtype: 'panel',
        region: 'center',
        itemId: 'content',
        reference: 'content',
        layout: 'card',
        items: [{
            xtype: "sggrid",
            region: 'center',
            columns: [{
                text: '行号', xtype: 'rownumberer',
                width: 50,
                sortable: false
            }, {
                text: 'ID',
                dataIndex: 'ID',
                hidden: true
            }, {
                text: '图纸状态',
                dataIndex: 'DrawingTask.TaskStatus',
                width: 100,
                renderer: function (v) {
                    if (Ext.isEmpty(v)) return "";
                    return serverNS.getComboStaticValue(ProjectInfoStaticData.DrawingTaskStatus, v);
                }
            }, {
                text: '公司名称',
                dataIndex: 'Company.Name',
                width: 100
            }, {
                text: '用户名称',
                dataIndex: 'User.Name',
                width: 100
            }, {
                text: '项目代码',
                dataIndex: 'ProjectNo',
                width: 100
            }, {
                text: '项目名称',
                dataIndex: 'ProjectName',
                width: 100
            }, {
                text: '合同号',
                dataIndex: 'ContractNo',
                width: 100
            }, {
                text: '客户名称',
                dataIndex: 'CustomerName',
                width: 100
            }, {
                text: '创建用户',
                dataIndex: 'CreateUser',
                width: 100
            }, {
                text: '创建日期',
                dataIndex: 'CreateDate',
                width: 200,
                renderer: Ext.util.Format.dateRenderer('m/d/Y H:i:s')
            }, {
                text: '项目状态',
                dataIndex: 'ProjectStatus',
                width: 100,
                hidden: true
            }, {
                text: '梯型ID',
                dataIndex: 'ModelID',
                width: 100,
                hidden: true
            }, {
                text: '版本号',
                dataIndex: 'ProjectVerNo',
                width: 100
            }, {
                text: '来源项目',
                dataIndex: 'ParentID',
                width: 100
            }, {
                text: '描述',
                dataIndex: 'Remark',
                width: 100
            }],
            listeners: {
                beforeload: "projectBeforeload"
            },
            quickSearchCols: ['Name', 'Code'],
            controllerUrl: 'Project',
            modelName: 'xf.model.project.Project',
            selfButtons: [SG_BUTTONS.ADD, SG_BUTTONS.EDIT, SG_BUTTONS.DELETE]
        }, {
            xtype: 'SGForm',
            apiUrl: '/Project',
            includePath: ["Company", "User","DrawingTask"],
            items: [{
                xtype: 'panel',
                title: '项目信息',
                columnWidth: 1,
                layout: 'column',
                defaults: {
                    border: 0,
                    padding: 5,
                    margin: 0,
                    xtype: 'textfield',
                    columnWidth: 0.3
                },
                items: [{
                    xtype: 'textfield',
                    fieldLabel: '公司',
                    readOnly: true,
                    name: 'Company.Name'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '用户',
                    readOnly: true,
                    name: 'User.Name'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '项目代码',
                    name: 'ProjectNo'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '项目名称',
                    name: 'ProjectName'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '合同号',
                    name: 'ContractNo'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '客户名称',
                    name: 'CustomerName'
                }, {
                    xtype: 'datefield',
                    fieldLabel: '创建日期',
                    readOnly: true,
                    format: "Y-m-d\\TH:i:s",
                    name: 'CreateDate',
                    hidden: true
                }, {
                    xtype: 'numberfield',
                    allowDecimals: false,
                    fieldLabel: '项目状态',
                    name: 'ProjectStatus',
                    hidden: true
                }, {
                    xtype: 'textfield',
                    fieldLabel: '梯型ID',
                    name: 'ModelID',
                    hidden: true
                }, {
                    xtype: 'textfield',
                    fieldLabel: '版本号',
                    name: 'ProjectVerNo',
                    hidden: true
                }, {
                    xtype: 'textfield',
                    fieldLabel: '来源项目',
                    name: 'ParentID',
                    hidden: true
                }, {
                    xtype: 'textfield',
                    fieldLabel: '绘图任务ID',
                    name: 'DrawingTaskID',
                    hidden: true
                }, {
                    xtype: 'textarea',
                    columnWidth: 1,
                    fieldLabel: '描述',
                    name: 'Remark',
                    hidden: true
                },]
            }, {
                xtype: 'panel',
                title: '公共参数',
                columnWidth: 1,
                layout: 'column',
                defaults: {
                    border: 0,
                    padding: 5,
                    margin: 0,
                    xtype: 'textfield',
                    columnWidth: 0.3
                },
                items: [{
                    xtype: 'textfield',
                    fieldLabel: '电梯型号',
                    name: 'ELEN'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '机房类型',
                    name: 'MRT'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '速度',
                    name: 'V'
                }]
            }, {
                xtype: 'panel',
                title: '主要参数',
                columnWidth: 1,
                layout: 'column',
                defaults: {
                    border: 0,
                    padding: 5,
                    margin: 0,
                    xtype: 'textfield',
                    columnWidth: 0.3
                },
                items: [{
                    xtype: 'textfield',
                    fieldLabel: '载重',
                    name: 'DL'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '对重位置',
                    name: 'CWTL'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '开门方式',
                    name: 'OPT'
                }]
            }, {
                xtype: 'panel',
                title: '井道平面',
                columnWidth: 1,
                layout: 'column',
                defaults: {
                    border: 0,
                    padding: 5,
                    margin: 0,
                    xtype: 'textfield',
                    columnWidth: 0.3
                },
                items: [{
                    xtype: 'textfield',
                    fieldLabel: '轿厢内宽',
                    name: 'DL'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '轿厢内深',
                    name: 'CWTL'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '前距',
                    name: 'OPT'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '井道宽度',
                    name: 'DL'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '井道深度',
                    name: 'CWTL'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '井道左内壁到轿厢距离',
                    name: 'OPT'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '开门宽',
                    name: 'OP'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '开门高',
                    name: 'OPH'
                }, {
                    xtype: 'textfield',
                    fieldLabel: '偏心方向',
                    name: 'OPT'
                }]
            }],
            selfButtons: [SG_BUTTONS.SAVE, {
                text: '生成图纸',
                iconCls: 'edit',
                handler: 'createDrawingTask'
            }, {
                    text: '下载图纸',
                    iconCls: 'download',
                    handler: 'downloadDrawingUrl'
                },  SG_BUTTONS.BACK]
        }]
    }]
});