Ext.define('xf.model.basedata.ParamDefine', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'ID',
        text: ''
    }, {
        name: 'Code',
        dtype: 'string',
        text: '代码'
    }, {
        name: 'Name',
        dtype: 'string',
        text: '名称'
    }, {
        name: 'Desc',
        dtype: 'string',
        text: '描述'
    }, {
        name: 'Unit',
        dtype: 'string',
        text: '单位'
    }, {
            name: 'ParamClass',
        dtype: 'string',
        text: '类别'
    }, {
        name: 'DefaultValue',
        dtype: 'string',
        text: '默认值'
    }, {
        name: 'DataType',
        dtype: 'string',
        text: '数据类型'
    }, {
        name: 'UseType',
        text: '使用类型'
    },  {
        name: 'Status',
        text: ''
    }, {
        name: 'CreateOn',
        dtype: 'date',
        text: ''
    }, {
        name: 'CreateBy',
        text: ''
    }, {
        name: 'UpdateOn',
        dtype: 'date',
        text: ''
    }, {
        name: 'UpdateBy',
        text: ''
    }],
    idProperty: 'ID'
});