Ext.define('xf.model.org.Company', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'ID',
        text: ''
    }, {
        name: 'Code',
        dtype: 'string',
        text: '编号'
    }, {
        name: 'Name',
        dtype: 'string',
        text: '名称'
    }, {
        name: 'Address',
        dtype: 'string',
        text: '地址'
    }, {
        name: 'Tel',
        dtype: 'string',
        text: '电话'
    }, {
        name: 'Email',
        dtype: 'string',
        text: '邮件'
    }, {
        name: 'Scale',
        dtype: 'string',
        text: '规模'
    }, {
        name: 'Level',
        text: '级别'
    }, {
        name: 'Remark',
        dtype: 'string',
        text: '描述'
    }, {
        name: 'Status',
        text: ''
    }, {
        name: 'CreateOn',
        dtype: 'date',
        xtype: 'data.field.date',
        format:'c',
        text: '创建时间'
    }, {
        name: 'CreateBy',
        text: ''
    }, {
        name: 'UpdateOn',
        dtype: 'date',
        xtype: 'date',
        format: 'c',
        text: ''
    }, {
        name: 'UpdateBy',
        text: ''
    }],
    idProperty: 'ID'
});