Ext.define('xf.model.org.Staff', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'ID',
        text: ''
    }, {
        name: 'Status',
        text: ''
    }, {
        name: 'CreateOn',
        dtype: 'date',
        text: ''
    }, {
        name: 'CreateBy',
        text: ''
    }, {
        name: 'UpdateOn',
        dtype: 'date',
        text: ''
    }, {
        name: 'UpdateBy',
        text: ''
    }, {
        name: 'CompanyID',
        text: '公司ID'
    }, {
        name: 'Company.Name',
        text: '公司名称'
    }, {
        name: 'Code',
        dtype: 'string',
        text: '用户编号'
    }, {
        name: 'Name',
        dtype: 'string',
        text: '名称'
    }, {
        name: 'Dept',
        dtype: 'string',
        text: '部门'
    }, {
        name: 'Phone',
        dtype: 'string',
        text: '电话'
    }, {
        name: 'Email',
        dtype: 'string',
        text: '邮件'
    },  {
        name: 'Gender',
        text: '性别'
    }, {
        name: 'Pwd',
        dtype: 'string',
        text: ''
    }, {
        name: 'Address',
        dtype: 'string',
        text: '地址'
    }, {
        name: 'LastLoginIp',
        dtype: 'string',
        text: '最后登录IP'
    }],
    idProperty: 'ID'
});